### ISSUE TITLE
Unbalanced or escaped quotes mess up highlighting

### ISSUE THREAD

**Issue by toote** [MaxGiting/atom-language-smarty#14]
When using functions that have unbalanced quotes (but still valid code) the highlighting interprets everything as a string afterwards.

Screenshots

* double quote within single quotes

![test1](https://user-images.githubusercontent.com/4922352/48381964-7cb14580-e6bd-11e8-8f05-cb07ac388dcb.png)

* escaped double quote within double quotes

![test2](https://user-images.githubusercontent.com/4922352/48381966-80dd6300-e6bd-11e8-8889-ba4f35edac1a.png)

**Comment by MaxGiting** [comment]
If you place the same code you screenshot and change the grammar to HTML the same issue occurs.

If you remove the `{{` and `}}` from your examples and the file is set to this Smarty Grammar there are still issues with highlighting.

Both of these lead me to believe it is the official HTML Grammar that has a highlighting issue as this plugin includes that Grammar.

**Comment by toote** [comment]
I understand... I thought that the parsing between ``{{}}`` was different (more PHP-like) and not just plain HTML - which that code is definitely not.

Unfortunately I don't understand atom parsing definitions enough to try to suggest an implementation (and the PHP one is very convoluted to try to use as an example of how to do it :P).

Thanks for your time!
