### ISSUE TITLE
Maximum call stack size exceeded on new window launch

### ISSUE THREAD

**Issue by timkelty** [MaxGiting/atom-language-smarty#6]
Getting this with the latest version installed: 
`Maximum call stack size exceeded`
1. Open Atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [language-smarty](https://github.com/MaxGiting/atom-language-smarty) package, v1.3.0
### Stack Trace

Failed to activate the language-smarty package

```
At Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at Object.module.exports.activate (/Users/timkelty/.atom/packages/language-smarty/index.coffee:3:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at Object.module.exports.activate (/Users/timkelty/.atom/packages/language-smarty/index.coffee:3:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "tomorrow-night-eighties-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "linter-csslint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
docblockr, v0.7.3
editorconfig, v1.2.2
emmet, v2.3.14
file-type-icons, v0.7.3
file-types, v0.5.1
html-entities, v0.4.0
javascript-snippets, v1.0.0
js-autoimport, v0.5.1
language-apache, v1.3.0
language-ini, v1.14.0
language-nunjucks, v2.0.0
linter, v1.10.0
linter-js-yaml, v1.2.0
linter-jshint, v1.2.1
linter-php, v1.1.0
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
markdown-preview-plus, v2.2.2
react, v0.12.10
set-syntax, v0.3.0
synced-sidebar, v0.4.2
tomorrow-night-eighties-syntax, v0.9.0

# Dev
No dev packages
```

**Comment by MaxGiting** [comment]
I haven't been able to replicate this on the same operating system and version of Atom. Could you please try without other packages.

I shall look into this, but it is a little hard without being able to achieve the same error.

**Comment by timkelty** [comment]
Yep, I'll try disabling everything else.

Also - FWIW, I just close the error bubble and continue on with no problems.

**Comment by MaxGiting** [comment]
Cheers, that's interesting.
The stack trace is actually looping. It looks like Package Manager is stuck endlessly activating the package. Not sure if that is what is actually happening as for me on multiple machines it's all working fine.

**Comment by timkelty** [comment]
I tried disabling all community plugins and still got the error.

**Comment by llagerlof** [comment]
This error happened to me today after plugin update. So I updated the Atom (Windows 8) too and the error vanished.

**Comment by timkelty** [comment]
Hmmm - I'm at latest (1.2) and still getting it.

Coworker is getting the same.

**Comment by llagerlof** [comment]
When I updated Atom I closed all files before the update.

I don't know if this was determinant to the problem solution, but try close all files and restart Atom.

**Comment by timkelty** [comment]
@llagerlof no luck :(

**Comment by llagerlof** [comment]
I think the comment of @abe33 in [this thread](https://github.com/abe33/atom-pigments/issues/19) could help @MaxGiting to find the solution:

> "Thanks to @crucialfelix I was able to find the cause of this infinite recursion. Bourbon (and probably many other) use tricks like `$border: grayscale($border)` and that was making fail the parsing of the value."

**Comment by MaxGiting** [comment]
Thank you both for your input. I think I have a fix. Could either / both of you edit the package files yourself? You would need to open up the settings for the package in atom and click view code. 

Then if you replace index.coffee with this 

```
module.exports =
  activate: (state) ->
      atom.packages.onDidActivatePackage (pack) ->
        if pack.name == 'language-smarty'
          path = require 'path'
          atom.workspace.observeTextEditors (editor) ->
              if path.extname(editor.getPath()) == ".tpl"
                editor.setGrammar(atom.grammars.grammarForScopeName('text.html.smarty'))
```

You will then need to save that file and reload atom. Either by closing it completely and opening it again or using the reload window command from within atom.

If neither of you can update the files manually I shall push a new release as I'm pretty sure this is the fix, but it would be good for you guys to test first.

**Comment by llagerlof** [comment]
Nice. I will not test this because my installation is working fine, but I am curious about the solution.

**Comment by timkelty** [comment]
@MaxGiting fixed! Thanks so much. I'll await a new published version :)
