### ISSUE TITLE
Add support for custom tags

### ISSUE THREAD

**Issue by hellboy81** [MaxGiting/atom-language-smarty#8]
```
"[{...}]"
```

should be also supported

**Comment by luison** [comment]
Also a must in our case. With so many configurable parameters the defined placeholder is a must. Thanks.

**Comment by MaxGiting** [comment]
To get this working you could edit smarty.cson and each of the instances of 
`\\{%?` to `\\[?\\{%?`
and
`%?\\}` to `\\}\\]?`

There are three of each and I believe this will fix the highlighting, but it will not change the snippets that this plugin generates.

A better solution would be to make this customisable in the settings page which would future proof it for everyone. I am open to PRs for this change.
